### ISSUE TITLE
Y'a une faute mon gars

### ISSUE THREAD

**Issue by MoniqueDumont** [Intempestif/exo-json-1#1]
le .sql est fourni. Y'a pas de "s" toi-même tu le saaaaaais

**Comment by Intempestif** [comment]
Merci

Le lun. 15 nov. 2021 à 08:39, MoniqueDumont ***@***.***> a
écrit :

**Comment by Intempestif** [comment]
cim cim

**Comment by Intempestif** [comment]
LGTM
